#############################################################################
# Makefile for building: cbapi-qt-demo
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  cbapi-qt-demo.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cbapi-qt-demo.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cbapi-qt-demo1.0.0
DISTDIR = /home/slist/cbapi-qt-demo/.tmp/cbapi-qt-demo1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = banned.cpp \
		droparea.cpp \
		edr.cpp \
		feed.cpp \
		instanceappcontrol.cpp \
		instanceedr.cpp \
		ioc.cpp \
		ioclist.cpp \
		iocs.cpp \
		iocsyntaxhighlighter.cpp \
		iplist.cpp \
		iplistadd.cpp \
		main.cpp \
		ngav.cpp \
		qjsonmodel.cpp \
		policy.cpp \
		difftool.cpp \
		instance.cpp \
		instances.cpp \
		policies.cpp \
		copy.cpp \
		homewindow.cpp \
		eraser.cpp \
		iocmainwindow.cpp \
		report.cpp \
		reportobject.cpp \
		servers.cpp \
		welcome.cpp qrc_cbapi-qt-demo.cpp \
		moc_banned.cpp \
		moc_droparea.cpp \
		moc_edr.cpp \
		moc_feed.cpp \
		moc_instanceappcontrol.cpp \
		moc_instanceedr.cpp \
		moc_ioc.cpp \
		moc_ioclist.cpp \
		moc_iocs.cpp \
		moc_iocsyntaxhighlighter.cpp \
		moc_iplist.cpp \
		moc_iplistadd.cpp \
		moc_ngav.cpp \
		moc_qjsonmodel.cpp \
		moc_report.cpp \
		moc_reportobject.cpp \
		moc_servers.cpp \
		moc_policy.cpp \
		moc_difftool.cpp \
		moc_instance.cpp \
		moc_instances.cpp \
		moc_policies.cpp \
		moc_copy.cpp \
		moc_homewindow.cpp \
		moc_eraser.cpp \
		moc_iocmainwindow.cpp \
		moc_welcome.cpp
OBJECTS       = banned.o \
		droparea.o \
		edr.o \
		feed.o \
		instanceappcontrol.o \
		instanceedr.o \
		ioc.o \
		ioclist.o \
		iocs.o \
		iocsyntaxhighlighter.o \
		iplist.o \
		iplistadd.o \
		main.o \
		ngav.o \
		qjsonmodel.o \
		policy.o \
		difftool.o \
		instance.o \
		instances.o \
		policies.o \
		copy.o \
		homewindow.o \
		eraser.o \
		iocmainwindow.o \
		report.o \
		reportobject.o \
		servers.o \
		welcome.o \
		qrc_cbapi-qt-demo.o \
		moc_banned.o \
		moc_droparea.o \
		moc_edr.o \
		moc_feed.o \
		moc_instanceappcontrol.o \
		moc_instanceedr.o \
		moc_ioc.o \
		moc_ioclist.o \
		moc_iocs.o \
		moc_iocsyntaxhighlighter.o \
		moc_iplist.o \
		moc_iplistadd.o \
		moc_ngav.o \
		moc_qjsonmodel.o \
		moc_report.o \
		moc_reportobject.o \
		moc_servers.o \
		moc_policy.o \
		moc_difftool.o \
		moc_instance.o \
		moc_instances.o \
		moc_policies.o \
		moc_copy.o \
		moc_homewindow.o \
		moc_eraser.o \
		moc_iocmainwindow.o \
		moc_welcome.o
DIST          = README.md \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cbapi-qt-demo.pro banned.h \
		droparea.h \
		edr.h \
		feed.h \
		instanceappcontrol.h \
		instanceedr.h \
		ioc.h \
		ioclist.h \
		iocs.h \
		iocsyntaxhighlighter.h \
		iplist.h \
		iplistadd.h \
		ngav.h \
		qjsonmodel.h \
		report.h \
		reportobject.h \
		servers.h \
		version.h \
		policy.h \
		difftool.h \
		instance.h \
		instances.h \
		policies.h \
		copy.h \
		homewindow.h \
		eraser.h \
		iocmainwindow.h \
		welcome.h banned.cpp \
		droparea.cpp \
		edr.cpp \
		feed.cpp \
		instanceappcontrol.cpp \
		instanceedr.cpp \
		ioc.cpp \
		ioclist.cpp \
		iocs.cpp \
		iocsyntaxhighlighter.cpp \
		iplist.cpp \
		iplistadd.cpp \
		main.cpp \
		ngav.cpp \
		qjsonmodel.cpp \
		policy.cpp \
		difftool.cpp \
		instance.cpp \
		instances.cpp \
		policies.cpp \
		copy.cpp \
		homewindow.cpp \
		eraser.cpp \
		iocmainwindow.cpp \
		report.cpp \
		reportobject.cpp \
		servers.cpp \
		welcome.cpp
QMAKE_TARGET  = cbapi-qt-demo
DESTDIR       = 
TARGET        = cbapi-qt-demo


first: all
####### Build rules

cbapi-qt-demo: ui_banned.h ui_edr.h ui_feed.h ui_instanceappcontrol.h ui_instanceedr.h ui_ioc.h ui_ioclist.h ui_iocs.h ui_iplist.h ui_iplistadd.h ui_ngav.h ui_policy.h ui_difftool.h ui_instance.h ui_instances.h ui_copy.h ui_homewindow.h ui_eraser.h ui_iocmainwindow.h ui_report.h ui_servers.h ui_welcome.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cbapi-qt-demo.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cbapi-qt-demo.pro \
		cbapi-qt-demo.qrc
	$(QMAKE) -o Makefile cbapi-qt-demo.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cbapi-qt-demo.pro:
cbapi-qt-demo.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile cbapi-qt-demo.pro

qmake_all: FORCE


all: Makefile cbapi-qt-demo

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents cbapi-qt-demo.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents banned.h droparea.h edr.h feed.h instanceappcontrol.h instanceedr.h ioc.h ioclist.h iocs.h iocsyntaxhighlighter.h iplist.h iplistadd.h ngav.h qjsonmodel.h report.h reportobject.h servers.h version.h policy.h difftool.h instance.h instances.h policies.h copy.h homewindow.h eraser.h iocmainwindow.h welcome.h $(DISTDIR)/
	$(COPY_FILE) --parents banned.cpp droparea.cpp edr.cpp feed.cpp instanceappcontrol.cpp instanceedr.cpp ioc.cpp ioclist.cpp iocs.cpp iocsyntaxhighlighter.cpp iplist.cpp iplistadd.cpp main.cpp ngav.cpp qjsonmodel.cpp policy.cpp difftool.cpp instance.cpp instances.cpp policies.cpp copy.cpp homewindow.cpp eraser.cpp iocmainwindow.cpp report.cpp reportobject.cpp servers.cpp welcome.cpp $(DISTDIR)/
	$(COPY_FILE) --parents banned.ui edr.ui feed.ui instanceappcontrol.ui instanceedr.ui ioc.ui ioclist.ui iocs.ui iplist.ui iplistadd.ui ngav.ui policy.ui difftool.ui instance.ui instances.ui copy.ui homewindow.ui eraser.ui iocmainwindow.ui report.ui servers.ui welcome.ui $(DISTDIR)/
	$(COPY_FILE) --parents cbapi-qt-demo_fr_FR.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_cbapi-qt-demo.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_cbapi-qt-demo.cpp
qrc_cbapi-qt-demo.cpp: cbapi-qt-demo.qrc \
		/usr/lib/qt5/bin/rcc \
		img/feed.png \
		img/cbeedr.png \
		img/workflow.png \
		img/help.png \
		img/open.png \
		img/qt-cbapi.png \
		img/onprem.png \
		img/dustbin.png \
		img/download.png \
		img/ip-list.png \
		img/watchlist.png \
		img/tools.png \
		img/cb.jpeg \
		img/watchlist_dark.png \
		img/appcontrol.png \
		img/extlink.png \
		img/json.png \
		img/cb-endpoint.png \
		img/cloud.png \
		img/save.png \
		img/banned.png \
		img/search.png \
		img/watchlist.svg \
		img/cancel.png \
		img/new.png \
		qdarkstyle/light/lightstyle.qss \
		qdarkstyle/light/lightstyle.qrc \
		qdarkstyle/light/rc/transparent.png \
		qdarkstyle/light/rc/line_horizontal_pressed.png \
		qdarkstyle/light/rc/line_horizontal.png \
		qdarkstyle/light/rc/arrow_left_disabled@2x.png \
		qdarkstyle/light/rc/branch_more_focus.png \
		qdarkstyle/light/rc/arrow_down_disabled@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical_pressed.png \
		qdarkstyle/light/rc/window_close_pressed@2x.png \
		qdarkstyle/light/rc/arrow_up_focus.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal_pressed@2x.png \
		qdarkstyle/light/rc/window_close_pressed.png \
		qdarkstyle/light/rc/branch_open_disabled@2x.png \
		qdarkstyle/light/rc/line_horizontal_focus@2x.png \
		qdarkstyle/light/rc/checkbox_unchecked.png \
		qdarkstyle/light/rc/radio_checked_focus@2x.png \
		qdarkstyle/light/rc/checkbox_checked_pressed@2x.png \
		qdarkstyle/light/rc/base_icon_disabled.png \
		qdarkstyle/light/rc/toolbar_move_horizontal.png \
		qdarkstyle/light/rc/window_close_disabled.png \
		qdarkstyle/light/rc/branch_line@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical@2x.png \
		qdarkstyle/light/rc/arrow_right_pressed@2x.png \
		qdarkstyle/light/rc/arrow_up_disabled.png \
		qdarkstyle/light/rc/checkbox_checked@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical_focus.png \
		qdarkstyle/light/rc/radio_unchecked_disabled.png \
		qdarkstyle/light/rc/checkbox_indeterminate.png \
		qdarkstyle/light/rc/window_close_disabled@2x.png \
		qdarkstyle/light/rc/window_grip_pressed@2x.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal_focus@2x.png \
		qdarkstyle/light/rc/branch_closed_disabled.png \
		qdarkstyle/light/rc/branch_line.png \
		qdarkstyle/light/rc/checkbox_indeterminate_pressed.png \
		qdarkstyle/light/rc/transparent_focus.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal.png \
		qdarkstyle/light/rc/branch_end_focus.png \
		qdarkstyle/light/rc/checkbox_unchecked@2x.png \
		qdarkstyle/light/rc/window_undock_disabled.png \
		qdarkstyle/light/rc/radio_checked_pressed@2x.png \
		qdarkstyle/light/rc/branch_end_focus@2x.png \
		qdarkstyle/light/rc/toolbar_move_horizontal_focus.png \
		qdarkstyle/light/rc/arrow_left_focus.png \
		qdarkstyle/light/rc/arrow_left@2x.png \
		qdarkstyle/light/rc/toolbar_separator_vertical_focus@2x.png \
		qdarkstyle/light/rc/window_grip_focus@2x.png \
		qdarkstyle/light/rc/window_undock_focus.png \
		qdarkstyle/light/rc/window_close.png \
		qdarkstyle/light/rc/line_horizontal@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical_disabled@2x.png \
		qdarkstyle/light/rc/line_vertical_focus@2x.png \
		qdarkstyle/light/rc/arrow_right@2x.png \
		qdarkstyle/light/rc/base_icon_pressed.png \
		qdarkstyle/light/rc/branch_line_focus.png \
		qdarkstyle/light/rc/window_grip_focus.png \
		qdarkstyle/light/rc/arrow_right_disabled@2x.png \
		qdarkstyle/light/rc/branch_more_pressed@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical_disabled.png \
		qdarkstyle/light/rc/arrow_up.png \
		qdarkstyle/light/rc/arrow_left_pressed@2x.png \
		qdarkstyle/light/rc/checkbox_checked.png \
		qdarkstyle/light/rc/toolbar_move_horizontal_disabled.png \
		qdarkstyle/light/rc/line_vertical_pressed.png \
		qdarkstyle/light/rc/base_icon_pressed@2x.png \
		qdarkstyle/light/rc/toolbar_separator_vertical_focus.png \
		qdarkstyle/light/rc/branch_end_pressed.png \
		qdarkstyle/light/rc/checkbox_indeterminate_focus@2x.png \
		qdarkstyle/light/rc/window_minimize_disabled.png \
		qdarkstyle/light/rc/window_undock_pressed.png \
		qdarkstyle/light/rc/radio_checked@2x.png \
		qdarkstyle/light/rc/toolbar_move_horizontal_disabled@2x.png \
		qdarkstyle/light/rc/branch_closed_disabled@2x.png \
		qdarkstyle/light/rc/line_vertical.png \
		qdarkstyle/light/rc/branch_line_disabled.png \
		qdarkstyle/light/rc/toolbar_separator_vertical.png \
		qdarkstyle/light/rc/branch_more_disabled.png \
		qdarkstyle/light/rc/toolbar_move_horizontal@2x.png \
		qdarkstyle/light/rc/window_undock_disabled@2x.png \
		qdarkstyle/light/rc/arrow_down_pressed.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal_disabled@2x.png \
		qdarkstyle/light/rc/branch_more_disabled@2x.png \
		qdarkstyle/light/rc/line_vertical_focus.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal@2x.png \
		qdarkstyle/light/rc/arrow_left_focus@2x.png \
		qdarkstyle/light/rc/transparent_focus@2x.png \
		qdarkstyle/light/rc/branch_open_focus@2x.png \
		qdarkstyle/light/rc/toolbar_separator_vertical_disabled@2x.png \
		qdarkstyle/light/rc/arrow_down_focus@2x.png \
		qdarkstyle/light/rc/arrow_up_pressed@2x.png \
		qdarkstyle/light/rc/arrow_up_disabled@2x.png \
		qdarkstyle/light/rc/checkbox_checked_disabled.png \
		qdarkstyle/light/rc/checkbox_checked_disabled@2x.png \
		qdarkstyle/light/rc/line_vertical@2x.png \
		qdarkstyle/light/rc/window_close@2x.png \
		qdarkstyle/light/rc/arrow_right_disabled.png \
		qdarkstyle/light/rc/branch_open@2x.png \
		qdarkstyle/light/rc/checkbox_unchecked_focus@2x.png \
		qdarkstyle/light/rc/line_vertical_disabled@2x.png \
		qdarkstyle/light/rc/branch_more.png \
		qdarkstyle/light/rc/transparent_pressed@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical.png \
		qdarkstyle/light/rc/line_horizontal_focus.png \
		qdarkstyle/light/rc/window_minimize_focus.png \
		qdarkstyle/light/rc/checkbox_indeterminate@2x.png \
		qdarkstyle/light/rc/branch_end_pressed@2x.png \
		qdarkstyle/light/rc/arrow_up_pressed.png \
		qdarkstyle/light/rc/arrow_right.png \
		qdarkstyle/light/rc/radio_checked_disabled@2x.png \
		qdarkstyle/light/rc/branch_open_pressed.png \
		qdarkstyle/light/rc/line_horizontal_disabled.png \
		qdarkstyle/light/rc/window_close_focus.png \
		qdarkstyle/light/rc/radio_checked_disabled.png \
		qdarkstyle/light/rc/branch_more@2x.png \
		qdarkstyle/light/rc/branch_open.png \
		qdarkstyle/light/rc/checkbox_unchecked_disabled@2x.png \
		qdarkstyle/light/rc/base_icon_focus@2x.png \
		qdarkstyle/light/rc/checkbox_unchecked_pressed.png \
		qdarkstyle/light/rc/window_close_focus@2x.png \
		qdarkstyle/light/rc/window_minimize_pressed@2x.png \
		qdarkstyle/light/rc/branch_closed.png \
		qdarkstyle/light/rc/arrow_up_focus@2x.png \
		qdarkstyle/light/rc/radio_checked_pressed.png \
		qdarkstyle/light/rc/branch_end_disabled@2x.png \
		qdarkstyle/light/rc/radio_unchecked_disabled@2x.png \
		qdarkstyle/light/rc/radio_unchecked_focus@2x.png \
		qdarkstyle/light/rc/base_icon@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical_pressed@2x.png \
		qdarkstyle/light/rc/toolbar_separator_vertical_pressed.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal_disabled.png \
		qdarkstyle/light/rc/branch_line_disabled@2x.png \
		qdarkstyle/light/rc/branch_closed_pressed.png \
		qdarkstyle/light/rc/branch_closed_focus@2x.png \
		qdarkstyle/light/rc/window_minimize@2x.png \
		qdarkstyle/light/rc/window_minimize.png \
		qdarkstyle/light/rc/transparent_pressed.png \
		qdarkstyle/light/rc/window_grip@2x.png \
		qdarkstyle/light/rc/checkbox_indeterminate_pressed@2x.png \
		qdarkstyle/light/rc/base_icon_focus.png \
		qdarkstyle/light/rc/checkbox_checked_pressed.png \
		qdarkstyle/light/rc/arrow_down_focus.png \
		qdarkstyle/light/rc/radio_checked.png \
		qdarkstyle/light/rc/branch_end_disabled.png \
		qdarkstyle/light/rc/toolbar_move_horizontal_pressed.png \
		qdarkstyle/light/rc/radio_unchecked_focus.png \
		qdarkstyle/light/rc/window_undock_focus@2x.png \
		qdarkstyle/light/rc/radio_unchecked_pressed.png \
		qdarkstyle/light/rc/toolbar_separator_vertical_disabled.png \
		qdarkstyle/light/rc/window_undock.png \
		qdarkstyle/light/rc/window_grip_disabled.png \
		qdarkstyle/light/rc/branch_open_pressed@2x.png \
		qdarkstyle/light/rc/radio_checked_focus.png \
		qdarkstyle/light/rc/checkbox_checked_focus.png \
		qdarkstyle/light/rc/window_undock_pressed@2x.png \
		qdarkstyle/light/rc/line_vertical_disabled.png \
		qdarkstyle/light/rc/checkbox_unchecked_focus.png \
		qdarkstyle/light/rc/branch_closed_focus.png \
		qdarkstyle/light/rc/arrow_down@2x.png \
		qdarkstyle/light/rc/toolbar_move_vertical_focus@2x.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal_focus.png \
		qdarkstyle/light/rc/window_grip_disabled@2x.png \
		qdarkstyle/light/rc/radio_unchecked.png \
		qdarkstyle/light/rc/checkbox_unchecked_pressed@2x.png \
		qdarkstyle/light/rc/window_grip.png \
		qdarkstyle/light/rc/toolbar_separator_vertical@2x.png \
		qdarkstyle/light/rc/arrow_right_focus.png \
		qdarkstyle/light/rc/toolbar_move_horizontal_focus@2x.png \
		qdarkstyle/light/rc/transparent_disabled@2x.png \
		qdarkstyle/light/rc/base_icon_disabled@2x.png \
		qdarkstyle/light/rc/window_grip_pressed.png \
		qdarkstyle/light/rc/base_icon.png \
		qdarkstyle/light/rc/transparent@2x.png \
		qdarkstyle/light/rc/arrow_up@2x.png \
		qdarkstyle/light/rc/line_vertical_pressed@2x.png \
		qdarkstyle/light/rc/line_horizontal_disabled@2x.png \
		qdarkstyle/light/rc/window_minimize_disabled@2x.png \
		qdarkstyle/light/rc/checkbox_indeterminate_disabled.png \
		qdarkstyle/light/rc/window_minimize_focus@2x.png \
		qdarkstyle/light/rc/window_undock@2x.png \
		qdarkstyle/light/rc/checkbox_indeterminate_disabled@2x.png \
		qdarkstyle/light/rc/branch_line_pressed@2x.png \
		qdarkstyle/light/rc/branch_line_focus@2x.png \
		qdarkstyle/light/rc/branch_line_pressed.png \
		qdarkstyle/light/rc/window_minimize_pressed.png \
		qdarkstyle/light/rc/radio_unchecked@2x.png \
		qdarkstyle/light/rc/checkbox_indeterminate_focus.png \
		qdarkstyle/light/rc/branch_closed_pressed@2x.png \
		qdarkstyle/light/rc/arrow_left.png \
		qdarkstyle/light/rc/toolbar_separator_vertical_pressed@2x.png \
		qdarkstyle/light/rc/branch_more_focus@2x.png \
		qdarkstyle/light/rc/line_horizontal_pressed@2x.png \
		qdarkstyle/light/rc/branch_more_pressed.png \
		qdarkstyle/light/rc/arrow_right_pressed.png \
		qdarkstyle/light/rc/arrow_down_pressed@2x.png \
		qdarkstyle/light/rc/toolbar_separator_horizontal_pressed.png \
		qdarkstyle/light/rc/branch_closed@2x.png \
		qdarkstyle/light/rc/branch_end@2x.png \
		qdarkstyle/light/rc/arrow_left_disabled.png \
		qdarkstyle/light/rc/transparent_disabled.png \
		qdarkstyle/light/rc/branch_open_disabled.png \
		qdarkstyle/light/rc/branch_open_focus.png \
		qdarkstyle/light/rc/arrow_down_disabled.png \
		qdarkstyle/light/rc/radio_unchecked_pressed@2x.png \
		qdarkstyle/light/rc/branch_end.png \
		qdarkstyle/light/rc/checkbox_unchecked_disabled.png \
		qdarkstyle/light/rc/checkbox_checked_focus@2x.png \
		qdarkstyle/light/rc/arrow_left_pressed.png \
		qdarkstyle/light/rc/arrow_down.png \
		qdarkstyle/light/rc/toolbar_move_horizontal_pressed@2x.png \
		qdarkstyle/light/rc/arrow_right_focus@2x.png \
		qdarkstyle/dark/darkstyle.qss \
		qdarkstyle/dark/darkstyle.qrc \
		qdarkstyle/dark/rc/transparent.png \
		qdarkstyle/dark/rc/line_horizontal_pressed.png \
		qdarkstyle/dark/rc/line_horizontal.png \
		qdarkstyle/dark/rc/arrow_left_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more_focus.png \
		qdarkstyle/dark/rc/arrow_down_disabled@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_pressed.png \
		qdarkstyle/dark/rc/window_close_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_focus.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_pressed@2x.png \
		qdarkstyle/dark/rc/window_close_pressed.png \
		qdarkstyle/dark/rc/branch_open_disabled@2x.png \
		qdarkstyle/dark/rc/line_horizontal_focus@2x.png \
		qdarkstyle/dark/rc/checkbox_unchecked.png \
		qdarkstyle/dark/rc/radio_checked_focus@2x.png \
		qdarkstyle/dark/rc/checkbox_checked_pressed@2x.png \
		qdarkstyle/dark/rc/base_icon_disabled.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal.png \
		qdarkstyle/dark/rc/window_close_disabled.png \
		qdarkstyle/dark/rc/branch_line@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical@2x.png \
		qdarkstyle/dark/rc/arrow_right_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_disabled.png \
		qdarkstyle/dark/rc/checkbox_checked@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_focus.png \
		qdarkstyle/dark/rc/radio_unchecked_disabled.png \
		qdarkstyle/dark/rc/checkbox_indeterminate.png \
		qdarkstyle/dark/rc/window_close_disabled@2x.png \
		qdarkstyle/dark/rc/window_grip_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_focus@2x.png \
		qdarkstyle/dark/rc/branch_closed_disabled.png \
		qdarkstyle/dark/rc/branch_line.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_pressed.png \
		qdarkstyle/dark/rc/transparent_focus.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal.png \
		qdarkstyle/dark/rc/branch_end_focus.png \
		qdarkstyle/dark/rc/checkbox_unchecked@2x.png \
		qdarkstyle/dark/rc/window_undock_disabled.png \
		qdarkstyle/dark/rc/radio_checked_pressed@2x.png \
		qdarkstyle/dark/rc/branch_end_focus@2x.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_focus.png \
		qdarkstyle/dark/rc/arrow_left_focus.png \
		qdarkstyle/dark/rc/arrow_left@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_focus@2x.png \
		qdarkstyle/dark/rc/window_grip_focus@2x.png \
		qdarkstyle/dark/rc/window_undock_focus.png \
		qdarkstyle/dark/rc/window_close.png \
		qdarkstyle/dark/rc/line_horizontal@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical_focus@2x.png \
		qdarkstyle/dark/rc/arrow_right@2x.png \
		qdarkstyle/dark/rc/base_icon_pressed.png \
		qdarkstyle/dark/rc/branch_line_focus.png \
		qdarkstyle/dark/rc/window_grip_focus.png \
		qdarkstyle/dark/rc/arrow_right_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_disabled.png \
		qdarkstyle/dark/rc/arrow_up.png \
		qdarkstyle/dark/rc/arrow_left_pressed@2x.png \
		qdarkstyle/dark/rc/checkbox_checked.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_disabled.png \
		qdarkstyle/dark/rc/line_vertical_pressed.png \
		qdarkstyle/dark/rc/base_icon_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_focus.png \
		qdarkstyle/dark/rc/branch_end_pressed.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_focus@2x.png \
		qdarkstyle/dark/rc/window_minimize_disabled.png \
		qdarkstyle/dark/rc/window_undock_pressed.png \
		qdarkstyle/dark/rc/radio_checked@2x.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_disabled@2x.png \
		qdarkstyle/dark/rc/branch_closed_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical.png \
		qdarkstyle/dark/rc/branch_line_disabled.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical.png \
		qdarkstyle/dark/rc/branch_more_disabled.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal@2x.png \
		qdarkstyle/dark/rc/window_undock_disabled@2x.png \
		qdarkstyle/dark/rc/arrow_down_pressed.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical_focus.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal@2x.png \
		qdarkstyle/dark/rc/arrow_left_focus@2x.png \
		qdarkstyle/dark/rc/transparent_focus@2x.png \
		qdarkstyle/dark/rc/branch_open_focus@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_disabled@2x.png \
		qdarkstyle/dark/rc/arrow_down_focus@2x.png \
		qdarkstyle/dark/rc/arrow_up_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_disabled@2x.png \
		qdarkstyle/dark/rc/checkbox_checked_disabled.png \
		qdarkstyle/dark/rc/checkbox_checked_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical@2x.png \
		qdarkstyle/dark/rc/window_close@2x.png \
		qdarkstyle/dark/rc/arrow_right_disabled.png \
		qdarkstyle/dark/rc/branch_open@2x.png \
		qdarkstyle/dark/rc/checkbox_unchecked_focus@2x.png \
		qdarkstyle/dark/rc/line_vertical_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more.png \
		qdarkstyle/dark/rc/transparent_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical.png \
		qdarkstyle/dark/rc/line_horizontal_focus.png \
		qdarkstyle/dark/rc/window_minimize_focus.png \
		qdarkstyle/dark/rc/checkbox_indeterminate@2x.png \
		qdarkstyle/dark/rc/branch_end_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_pressed.png \
		qdarkstyle/dark/rc/arrow_right.png \
		qdarkstyle/dark/rc/radio_checked_disabled@2x.png \
		qdarkstyle/dark/rc/branch_open_pressed.png \
		qdarkstyle/dark/rc/line_horizontal_disabled.png \
		qdarkstyle/dark/rc/window_close_focus.png \
		qdarkstyle/dark/rc/radio_checked_disabled.png \
		qdarkstyle/dark/rc/branch_more@2x.png \
		qdarkstyle/dark/rc/branch_open.png \
		qdarkstyle/dark/rc/checkbox_unchecked_disabled@2x.png \
		qdarkstyle/dark/rc/base_icon_focus@2x.png \
		qdarkstyle/dark/rc/checkbox_unchecked_pressed.png \
		qdarkstyle/dark/rc/window_close_focus@2x.png \
		qdarkstyle/dark/rc/window_minimize_pressed@2x.png \
		qdarkstyle/dark/rc/branch_closed.png \
		qdarkstyle/dark/rc/arrow_up_focus@2x.png \
		qdarkstyle/dark/rc/radio_checked_pressed.png \
		qdarkstyle/dark/rc/branch_end_disabled@2x.png \
		qdarkstyle/dark/rc/radio_unchecked_disabled@2x.png \
		qdarkstyle/dark/rc/radio_unchecked_focus@2x.png \
		qdarkstyle/dark/rc/base_icon@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_pressed.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_disabled.png \
		qdarkstyle/dark/rc/branch_line_disabled@2x.png \
		qdarkstyle/dark/rc/branch_closed_pressed.png \
		qdarkstyle/dark/rc/branch_closed_focus@2x.png \
		qdarkstyle/dark/rc/window_minimize@2x.png \
		qdarkstyle/dark/rc/window_minimize.png \
		qdarkstyle/dark/rc/transparent_pressed.png \
		qdarkstyle/dark/rc/window_grip@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_pressed@2x.png \
		qdarkstyle/dark/rc/base_icon_focus.png \
		qdarkstyle/dark/rc/checkbox_checked_pressed.png \
		qdarkstyle/dark/rc/arrow_down_focus.png \
		qdarkstyle/dark/rc/radio_checked.png \
		qdarkstyle/dark/rc/branch_end_disabled.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_pressed.png \
		qdarkstyle/dark/rc/radio_unchecked_focus.png \
		qdarkstyle/dark/rc/window_undock_focus@2x.png \
		qdarkstyle/dark/rc/radio_unchecked_pressed.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_disabled.png \
		qdarkstyle/dark/rc/window_undock.png \
		qdarkstyle/dark/rc/window_grip_disabled.png \
		qdarkstyle/dark/rc/branch_open_pressed@2x.png \
		qdarkstyle/dark/rc/radio_checked_focus.png \
		qdarkstyle/dark/rc/checkbox_checked_focus.png \
		qdarkstyle/dark/rc/window_undock_pressed@2x.png \
		qdarkstyle/dark/rc/line_vertical_disabled.png \
		qdarkstyle/dark/rc/checkbox_unchecked_focus.png \
		qdarkstyle/dark/rc/branch_closed_focus.png \
		qdarkstyle/dark/rc/arrow_down@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_focus@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_focus.png \
		qdarkstyle/dark/rc/window_grip_disabled@2x.png \
		qdarkstyle/dark/rc/radio_unchecked.png \
		qdarkstyle/dark/rc/checkbox_unchecked_pressed@2x.png \
		qdarkstyle/dark/rc/window_grip.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical@2x.png \
		qdarkstyle/dark/rc/arrow_right_focus.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_focus@2x.png \
		qdarkstyle/dark/rc/transparent_disabled@2x.png \
		qdarkstyle/dark/rc/base_icon_disabled@2x.png \
		qdarkstyle/dark/rc/window_grip_pressed.png \
		qdarkstyle/dark/rc/base_icon.png \
		qdarkstyle/dark/rc/transparent@2x.png \
		qdarkstyle/dark/rc/arrow_up@2x.png \
		qdarkstyle/dark/rc/line_vertical_pressed@2x.png \
		qdarkstyle/dark/rc/line_horizontal_disabled@2x.png \
		qdarkstyle/dark/rc/window_minimize_disabled@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_disabled.png \
		qdarkstyle/dark/rc/window_minimize_focus@2x.png \
		qdarkstyle/dark/rc/window_undock@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_disabled@2x.png \
		qdarkstyle/dark/rc/branch_line_pressed@2x.png \
		qdarkstyle/dark/rc/branch_line_focus@2x.png \
		qdarkstyle/dark/rc/branch_line_pressed.png \
		qdarkstyle/dark/rc/window_minimize_pressed.png \
		qdarkstyle/dark/rc/radio_unchecked@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_focus.png \
		qdarkstyle/dark/rc/branch_closed_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_left.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_pressed@2x.png \
		qdarkstyle/dark/rc/branch_more_focus@2x.png \
		qdarkstyle/dark/rc/line_horizontal_pressed@2x.png \
		qdarkstyle/dark/rc/branch_more_pressed.png \
		qdarkstyle/dark/rc/arrow_right_pressed.png \
		qdarkstyle/dark/rc/arrow_down_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_pressed.png \
		qdarkstyle/dark/rc/branch_closed@2x.png \
		qdarkstyle/dark/rc/branch_end@2x.png \
		qdarkstyle/dark/rc/arrow_left_disabled.png \
		qdarkstyle/dark/rc/transparent_disabled.png \
		qdarkstyle/dark/rc/branch_open_disabled.png \
		qdarkstyle/dark/rc/branch_open_focus.png \
		qdarkstyle/dark/rc/arrow_down_disabled.png \
		qdarkstyle/dark/rc/radio_unchecked_pressed@2x.png \
		qdarkstyle/dark/rc/branch_end.png \
		qdarkstyle/dark/rc/checkbox_unchecked_disabled.png \
		qdarkstyle/dark/rc/checkbox_checked_focus@2x.png \
		qdarkstyle/dark/rc/arrow_left_pressed.png \
		qdarkstyle/dark/rc/arrow_down.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_right_focus@2x.png
	/usr/lib/qt5/bin/rcc -name cbapi-qt-demo cbapi-qt-demo.qrc -o qrc_cbapi-qt-demo.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_banned.cpp moc_droparea.cpp moc_edr.cpp moc_feed.cpp moc_instanceappcontrol.cpp moc_instanceedr.cpp moc_ioc.cpp moc_ioclist.cpp moc_iocs.cpp moc_iocsyntaxhighlighter.cpp moc_iplist.cpp moc_iplistadd.cpp moc_ngav.cpp moc_qjsonmodel.cpp moc_report.cpp moc_reportobject.cpp moc_servers.cpp moc_policy.cpp moc_difftool.cpp moc_instance.cpp moc_instances.cpp moc_policies.cpp moc_copy.cpp moc_homewindow.cpp moc_eraser.cpp moc_iocmainwindow.cpp moc_welcome.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_banned.cpp moc_droparea.cpp moc_edr.cpp moc_feed.cpp moc_instanceappcontrol.cpp moc_instanceedr.cpp moc_ioc.cpp moc_ioclist.cpp moc_iocs.cpp moc_iocsyntaxhighlighter.cpp moc_iplist.cpp moc_iplistadd.cpp moc_ngav.cpp moc_qjsonmodel.cpp moc_report.cpp moc_reportobject.cpp moc_servers.cpp moc_policy.cpp moc_difftool.cpp moc_instance.cpp moc_instances.cpp moc_policies.cpp moc_copy.cpp moc_homewindow.cpp moc_eraser.cpp moc_iocmainwindow.cpp moc_welcome.cpp
moc_banned.cpp: banned.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include banned.h -o moc_banned.cpp

moc_droparea.cpp: droparea.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include droparea.h -o moc_droparea.cpp

moc_edr.cpp: edr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include edr.h -o moc_edr.cpp

moc_feed.cpp: feed.h \
		report.h \
		iocsyntaxhighlighter.h \
		reportobject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include feed.h -o moc_feed.cpp

moc_instanceappcontrol.cpp: instanceappcontrol.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include instanceappcontrol.h -o moc_instanceappcontrol.cpp

moc_instanceedr.cpp: instanceedr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include instanceedr.h -o moc_instanceedr.cpp

moc_ioc.cpp: ioc.h \
		iocsyntaxhighlighter.h \
		feed.h \
		report.h \
		reportobject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ioc.h -o moc_ioc.cpp

moc_ioclist.cpp: ioclist.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ioclist.h -o moc_ioclist.cpp

moc_iocs.cpp: iocs.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include iocs.h -o moc_iocs.cpp

moc_iocsyntaxhighlighter.cpp: iocsyntaxhighlighter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include iocsyntaxhighlighter.h -o moc_iocsyntaxhighlighter.cpp

moc_iplist.cpp: iplist.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include iplist.h -o moc_iplist.cpp

moc_iplistadd.cpp: iplistadd.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include iplistadd.h -o moc_iplistadd.cpp

moc_ngav.cpp: ngav.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ngav.h -o moc_ngav.cpp

moc_qjsonmodel.cpp: qjsonmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include qjsonmodel.h -o moc_qjsonmodel.cpp

moc_report.cpp: report.h \
		iocsyntaxhighlighter.h \
		reportobject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include report.h -o moc_report.cpp

moc_reportobject.cpp: reportobject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include reportobject.h -o moc_reportobject.cpp

moc_servers.cpp: servers.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include servers.h -o moc_servers.cpp

moc_policy.cpp: policy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include policy.h -o moc_policy.cpp

moc_difftool.cpp: difftool.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include difftool.h -o moc_difftool.cpp

moc_instance.cpp: instance.h \
		instances.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include instance.h -o moc_instance.cpp

moc_instances.cpp: instances.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include instances.h -o moc_instances.cpp

moc_policies.cpp: policies.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include policies.h -o moc_policies.cpp

moc_copy.cpp: copy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include copy.h -o moc_copy.cpp

moc_homewindow.cpp: homewindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include homewindow.h -o moc_homewindow.cpp

moc_eraser.cpp: eraser.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include eraser.h -o moc_eraser.cpp

moc_iocmainwindow.cpp: iocmainwindow.h \
		iocsyntaxhighlighter.h \
		feed.h \
		report.h \
		reportobject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include iocmainwindow.h -o moc_iocmainwindow.cpp

moc_welcome.cpp: welcome.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/slist/cbapi-qt-demo/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/slist/cbapi-qt-demo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include welcome.h -o moc_welcome.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_banned.h ui_edr.h ui_feed.h ui_instanceappcontrol.h ui_instanceedr.h ui_ioc.h ui_ioclist.h ui_iocs.h ui_iplist.h ui_iplistadd.h ui_ngav.h ui_policy.h ui_difftool.h ui_instance.h ui_instances.h ui_copy.h ui_homewindow.h ui_eraser.h ui_iocmainwindow.h ui_report.h ui_servers.h ui_welcome.h
compiler_uic_clean:
	-$(DEL_FILE) ui_banned.h ui_edr.h ui_feed.h ui_instanceappcontrol.h ui_instanceedr.h ui_ioc.h ui_ioclist.h ui_iocs.h ui_iplist.h ui_iplistadd.h ui_ngav.h ui_policy.h ui_difftool.h ui_instance.h ui_instances.h ui_copy.h ui_homewindow.h ui_eraser.h ui_iocmainwindow.h ui_report.h ui_servers.h ui_welcome.h
ui_banned.h: banned.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic banned.ui -o ui_banned.h

ui_edr.h: edr.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic edr.ui -o ui_edr.h

ui_feed.h: feed.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic feed.ui -o ui_feed.h

ui_instanceappcontrol.h: instanceappcontrol.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic instanceappcontrol.ui -o ui_instanceappcontrol.h

ui_instanceedr.h: instanceedr.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic instanceedr.ui -o ui_instanceedr.h

ui_ioc.h: ioc.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ioc.ui -o ui_ioc.h

ui_ioclist.h: ioclist.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ioclist.ui -o ui_ioclist.h

ui_iocs.h: iocs.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic iocs.ui -o ui_iocs.h

ui_iplist.h: iplist.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic iplist.ui -o ui_iplist.h

ui_iplistadd.h: iplistadd.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic iplistadd.ui -o ui_iplistadd.h

ui_ngav.h: ngav.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ngav.ui -o ui_ngav.h

ui_policy.h: policy.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic policy.ui -o ui_policy.h

ui_difftool.h: difftool.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic difftool.ui -o ui_difftool.h

ui_instance.h: instance.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic instance.ui -o ui_instance.h

ui_instances.h: instances.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic instances.ui -o ui_instances.h

ui_copy.h: copy.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic copy.ui -o ui_copy.h

ui_homewindow.h: homewindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic homewindow.ui -o ui_homewindow.h

ui_eraser.h: eraser.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic eraser.ui -o ui_eraser.h

ui_iocmainwindow.h: iocmainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic iocmainwindow.ui -o ui_iocmainwindow.h

ui_report.h: report.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic report.ui -o ui_report.h

ui_servers.h: servers.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic servers.ui -o ui_servers.h

ui_welcome.h: welcome.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic welcome.ui -o ui_welcome.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

banned.o: banned.cpp banned.h \
		ui_banned.h \
		droparea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o banned.o banned.cpp

droparea.o: droparea.cpp droparea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o droparea.o droparea.cpp

edr.o: edr.cpp edr.h \
		ui_edr.h \
		qjsonmodel.h \
		eraser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edr.o edr.cpp

feed.o: feed.cpp feed.h \
		report.h \
		iocsyntaxhighlighter.h \
		reportobject.h \
		ui_feed.h \
		qjsonmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o feed.o feed.cpp

instanceappcontrol.o: instanceappcontrol.cpp instanceappcontrol.h \
		ui_instanceappcontrol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instanceappcontrol.o instanceappcontrol.cpp

instanceedr.o: instanceedr.cpp instanceedr.h \
		ui_instanceedr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instanceedr.o instanceedr.cpp

ioc.o: ioc.cpp ioc.h \
		iocsyntaxhighlighter.h \
		feed.h \
		report.h \
		reportobject.h \
		ui_ioc.h \
		qjsonmodel.h \
		ioclist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioc.o ioc.cpp

ioclist.o: ioclist.cpp ioclist.h \
		ui_ioclist.h \
		iocsyntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioclist.o ioclist.cpp

iocs.o: iocs.cpp iocs.h \
		ui_iocs.h \
		ioc.h \
		iocsyntaxhighlighter.h \
		feed.h \
		report.h \
		reportobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iocs.o iocs.cpp

iocsyntaxhighlighter.o: iocsyntaxhighlighter.cpp iocsyntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iocsyntaxhighlighter.o iocsyntaxhighlighter.cpp

iplist.o: iplist.cpp iplist.h \
		ui_iplist.h \
		iplistadd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iplist.o iplist.cpp

iplistadd.o: iplistadd.cpp iplistadd.h \
		ui_iplistadd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iplistadd.o iplistadd.cpp

main.o: main.cpp homewindow.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ngav.o: ngav.cpp ngav.h \
		ui_ngav.h \
		difftool.h \
		copy.h \
		policies.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ngav.o ngav.cpp

qjsonmodel.o: qjsonmodel.cpp qjsonmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjsonmodel.o qjsonmodel.cpp

policy.o: policy.cpp policy.h \
		ui_policy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o policy.o policy.cpp

difftool.o: difftool.cpp difftool.h \
		ui_difftool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o difftool.o difftool.cpp

instance.o: instance.cpp instance.h \
		instances.h \
		ui_instance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instance.o instance.cpp

instances.o: instances.cpp instance.h \
		instances.h \
		instanceedr.h \
		instanceappcontrol.h \
		ui_instances.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instances.o instances.cpp

policies.o: policies.cpp policy.h \
		policies.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o policies.o policies.cpp

copy.o: copy.cpp copy.h \
		ui_copy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o copy.o copy.cpp

homewindow.o: homewindow.cpp homewindow.h \
		ui_homewindow.h \
		ngav.h \
		edr.h \
		iocmainwindow.h \
		iocsyntaxhighlighter.h \
		feed.h \
		report.h \
		reportobject.h \
		welcome.h \
		iocs.h \
		servers.h \
		iplist.h \
		banned.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o homewindow.o homewindow.cpp

eraser.o: eraser.cpp eraser.h \
		ui_eraser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eraser.o eraser.cpp

iocmainwindow.o: iocmainwindow.cpp iocmainwindow.h \
		iocsyntaxhighlighter.h \
		feed.h \
		report.h \
		reportobject.h \
		ui_iocmainwindow.h \
		qjsonmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iocmainwindow.o iocmainwindow.cpp

report.o: report.cpp report.h \
		iocsyntaxhighlighter.h \
		reportobject.h \
		ui_report.h \
		qjsonmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o report.o report.cpp

reportobject.o: reportobject.cpp reportobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reportobject.o reportobject.cpp

servers.o: servers.cpp servers.h \
		ui_servers.h \
		homewindow.h \
		instances.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servers.o servers.cpp

welcome.o: welcome.cpp welcome.h \
		ui_welcome.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o welcome.o welcome.cpp

qrc_cbapi-qt-demo.o: qrc_cbapi-qt-demo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_cbapi-qt-demo.o qrc_cbapi-qt-demo.cpp

moc_banned.o: moc_banned.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_banned.o moc_banned.cpp

moc_droparea.o: moc_droparea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_droparea.o moc_droparea.cpp

moc_edr.o: moc_edr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edr.o moc_edr.cpp

moc_feed.o: moc_feed.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_feed.o moc_feed.cpp

moc_instanceappcontrol.o: moc_instanceappcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instanceappcontrol.o moc_instanceappcontrol.cpp

moc_instanceedr.o: moc_instanceedr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instanceedr.o moc_instanceedr.cpp

moc_ioc.o: moc_ioc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ioc.o moc_ioc.cpp

moc_ioclist.o: moc_ioclist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ioclist.o moc_ioclist.cpp

moc_iocs.o: moc_iocs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iocs.o moc_iocs.cpp

moc_iocsyntaxhighlighter.o: moc_iocsyntaxhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iocsyntaxhighlighter.o moc_iocsyntaxhighlighter.cpp

moc_iplist.o: moc_iplist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iplist.o moc_iplist.cpp

moc_iplistadd.o: moc_iplistadd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iplistadd.o moc_iplistadd.cpp

moc_ngav.o: moc_ngav.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ngav.o moc_ngav.cpp

moc_qjsonmodel.o: moc_qjsonmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjsonmodel.o moc_qjsonmodel.cpp

moc_report.o: moc_report.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_report.o moc_report.cpp

moc_reportobject.o: moc_reportobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reportobject.o moc_reportobject.cpp

moc_servers.o: moc_servers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_servers.o moc_servers.cpp

moc_policy.o: moc_policy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_policy.o moc_policy.cpp

moc_difftool.o: moc_difftool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_difftool.o moc_difftool.cpp

moc_instance.o: moc_instance.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instance.o moc_instance.cpp

moc_instances.o: moc_instances.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instances.o moc_instances.cpp

moc_policies.o: moc_policies.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_policies.o moc_policies.cpp

moc_copy.o: moc_copy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_copy.o moc_copy.cpp

moc_homewindow.o: moc_homewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_homewindow.o moc_homewindow.cpp

moc_eraser.o: moc_eraser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eraser.o moc_eraser.cpp

moc_iocmainwindow.o: moc_iocmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iocmainwindow.o moc_iocmainwindow.cpp

moc_welcome.o: moc_welcome.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_welcome.o moc_welcome.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

