name: Linux Qt6 Release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'master'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.5.0
  ARTIFACT:     cbapi-qt-demo-linux-build.AppImage

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Update packages list
      run: sudo apt update
      
    - name: Install packages
      run: sudo apt install cppcheck cpplint

    - name: Run cppcheck (unused functions)
      working-directory: ${{ env.SOURCE_DIR }}
      run: cppcheck --enable=unusedFunction --language=c++ $(find -name "*.h" -o -name "*.cpp")
      continue-on-error: true

    - name: Run cppcheck (warnings and performance issues)
      working-directory: ${{ env.SOURCE_DIR }}
      run: cppcheck --enable=warning,performance --language=c++ $(find -name "*.h" -o -name "*.cpp")

    - name: Run cpplint
      working-directory: ${{ env.SOURCE_DIR }}
      run: cpplint --filter=-build/include_subdir,-build/include_order,-whitespace,-build/header_guard,-readability/todo --linelength=120 $(find -name "*.h" -o -name "*.cpp")

  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: ${{ env.QT_VERSION }}
          modules: 'qt5compat'
          setup-python: false
              
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run:  |
              qmake -r ${{ env.SOURCE_DIR }}/cbapi-qt-demo.pro
              make -j`nproc`

